### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by kyriosdata** [rnds-tools/gui#1]
## Contexto

A interação com o servidor FHIR (mock) pode ser realizada por código produzido pelo integrador, cliente como Postman e outros. Além destas possibilidades, duas são oferecidas pelo Ambiente de Desenvolvimento: uma gráfica e outra via linha de comandos rnds-tools/start#2. 

Uma inspiração pode ser obtida [aqui](http://hapi.fhir.org/), que já fornece exemplos e permite requisições. O [código fonte](https://github.com/hapifhir/hapi-fhir-jpaserver-starter) para detalhes.

## Requisitos GUI

Um conjunto preliminar de características esperadas na interface gráfica é fornecido abaixo:

- Edição de instâncias de recursos FHIR. Conformidade com o padrão FHIR para os elementos, campos, deve ser assegurada. 
- Deve ser possível gerar versão PDF de cada instância com formato “atrativo”.
- Deve ser possível a edição de instâncias de recursos empregados pela RNDS. A edição deve estar em conformidade com os perfis nacionais. Todas os tipos de _resources_ empregados pela RNDS devem estar disponíveis para edição (criação de instâncias).
- A GUI deve ser implementada como uma SPA, o que mantém o servidor FHIR isolado de questões de interface com o usuário. Neste cenário, a GUI é “similar” ao Postman, onde o **body** teria um formulário para preenchimento e validação conforme os perfis nacionais. 
- Submissão de requisições em conformidade com interações e operações definidas pela RNDS.
- Configuração dos profiles a serem empregados com recursos para adição, substituição e remoção daqueles considerados, em tempo de execução.

## Design

- Pode ser implementada como SPA sem necessidade de interação com servidor remoto? Validação, TerminologyService e demais? Isso facilitaria implantação e não demandaria servidor remoto.
- Conversões de JSON para XML e de XML para JSON e validações podem ser feitas com [fhir.js](https://github.com/lantanagroup/FHIR.js)
- Apenas cliente FHIR em JS [aqui](https://github.com/FHIR/fhir.js?_ga=2.75210970.976529887.1662986576-1215025224.1662986575)
- Várias ferramentas que usam FHIR por meio de [JS](https://npm.io/search/keyword:fhir)

**Comment by nogueiralegacy** [comment]
Na seçõa Design está escrito "Json/XML/Json"

**Comment by kyriosdata** [comment]
Documentação disponível no readme.md
